services:
  redis:
    build:
      dockerfile: docker/redis.Dockerfile
    networks:
      - internal
  kv-dev:
    build:
      dockerfile: docker/kv-dev.Dockerfile
    ports:
      - "8080:3000"
    environment:
      REDIS_URL: http://redis:4000
    depends_on:
      - redis
    volumes:
      - ./kv-server:/app/kv-server
      - /app/node_modules
    networks:
      - internal


networks:
  internal:
